Repository kubevirt/user-guide, pull requests merged in 2018-11, with the labels that each got.

#137 disks cache doc
  workloads/virtual-machines/disks-and-volumes.md
Labels: size/M

#139 Document node problem behaviour
  _sidebar.md
  workloads/virtual-machines/unresponsive-nodes.md
Labels: size/M

#141 document the virtio-net multiqueue
  workloads/virtual-machines/interfaces-and-networks.md
Labels: size/M

#143 Fix minor typos in Presets doc
  workloads/virtual-machines/presets.md
Labels: size/XS

#142 document IOThreads pinning to pCPUs
  workloads/virtual-machines/disks-and-volumes.md
Labels: size/XS

#144 adding genie documentation
  workloads/virtual-machines/interfaces-and-networks.md
Labels: size/M

#138 network: plugins installation documentation
  installation/README.md
Labels: size/S

#140 Document vmctl overview and usage
  workloads/virtual-machines/vmctl.md
Labels: size/L

#148 Use latest release
  installation/README.md
Labels: size/XS

#147 Fix link to kubevirt-incubator
  additional-resources.md
Labels: size/XS

#146 fixes from PR #144
  workloads/virtual-machines/interfaces-and-networks.md
Labels: size/S

#149 Add clarifications to vmctl examples and usage
  workloads/virtual-machines/vmctl.md
Labels: size/S

#134 Document `sriov` interface mode
  workloads/virtual-machines/interfaces-and-networks.md
Labels: size/M

#153 Added note about tolerating smaller PVs, and use links for disk/volume types
  workloads/virtual-machines/disks-and-volumes.md
Labels: size/M

#154 Fix link to CPU models
  workloads/virtual-machines/virtualized-hardware-configuration.md
Labels: size/XS

#158 fix NetworkPolicy case
  _sidebar.md
  workloads/virtual-machines/create-networkpolicy.md
Labels: size/XS

#161 correct link to the user guide
  README.md
Labels: size/XS

#155 Rename registryDisk to containerDisk
  .aspell.en.pws
  workloads/controllers/virtual-machine-replica-set.md
  workloads/controllers/virtual-machine.md
  workloads/virtual-machines/creation.md
  workloads/virtual-machines/disks-and-volumes.md
  workloads/virtual-machines/dns.md
  workloads/virtual-machines/expose-service.md
  workloads/virtual-machines/startup-scripts.md
Labels: size/L

#163 Change kubevit-config to kubevirt-config .
  workloads/virtual-machines/disks-and-volumes.md
Labels: size/XS

#162 Change speical to special.
  workloads/virtual-machines/expose-service.md
Labels: size/XS

#156 Sriov feature gate
  workloads/virtual-machines/interfaces-and-networks.md
Labels: size/M
