Repository kubevirt/user-guide, pull requests merged in 2018-12, with the labels that each got.

#152 Document liveness- and readiness probes
  _sidebar.md
  workloads/virtual-machines/probes.md
Labels: size/L

#151 Document what users can do with the "common templates" subproject
  _sidebar.md
  workloads/templates/common-templates.md
Labels: size/L

#157 Update sriov documentation to reflect the latest sriovdp master
  workloads/virtual-machines/interfaces-and-networks.md
Labels: size/XS

#160 Remove references to vmctl ServiceAccount from examples
  workloads/virtual-machines/vmctl.md
Labels: size/XS

#167 Update sriov docs to not include explicit device requests
  workloads/virtual-machines/interfaces-and-networks.md
Labels: size/M

#171 Fix indocument links in disk-and-volumes doc
  workloads/virtual-machines/disks-and-volumes.md
Labels: size/M

#169 Add status parameter to DataVolume example
  workloads/virtual-machines/disks-and-volumes.md
Labels: size/S

#166 Variable declaration missing for OpenShift
  installation/README.md
Labels: size/S

#159 Change references to KubeVirt default namespace
  installation/README.md
  misc/monitoring.md
  workloads/virtual-machines/dedicated-cpu.md
  workloads/virtual-machines/disks-and-volumes.md
Labels: size/S

#176 With changelog
  .gitignore
  _topic_map.yml
  release-notes/changelog.adoc
  release-notes/update_changelog.sh
Labels: size/L

#181 With fixed asciidoc
  .gitignore
  .travis.yml
  Makefile
  README.md
  _coverpage.md
  _images/KubeVirt_icon.png
  _images/kubevirt-pre-256x256.png
  _sidebar.md
  _templates/page.html.erb
  _topic_map.yml
  additional-resources.md
  authorization.md
  index-community.html
  index-kubevirt-community.html
  index.html
  installation/README.md
  installation/api-validation.md
  installation/feature-matrix.md
  misc/annotations_and_labels.md
  misc/monitoring.md
  usage.md
  welcome/additional-resources.adoc
  welcome/index.adoc
  workloads/README.md
  workloads/controllers/README.md
  workloads/controllers/virtual-machine-replica-set.md
  workloads/controllers/virtual-machine.md
  workloads/templates/README.md
  workloads/templates/common-templates.md
  workloads/templates/vm-creation.md
  workloads/virtual-machines/README.md
  workloads/virtual-machines/assigning-vms-to-nodes.md
  workloads/virtual-machines/create-networkpolicy.md
  workloads/virtual-machines/creation.md
  workloads/virtual-machines/dedicated-cpu.md
  workloads/virtual-machines/disks-and-volumes.md
  workloads/virtual-machines/dns.md
  workloads/virtual-machines/expose-service.md
  workloads/virtual-machines/graphical-and-console-access.md
  workloads/virtual-machines/guest-operating-system-information.md
  workloads/virtual-machines/image-upload.md
  workloads/virtual-machines/interfaces-and-networks.md
  workloads/virtual-machines/life-cycle.md
  workloads/virtual-machines/node-eviction.md
  workloads/virtual-machines/overcommit.md
  workloads/virtual-machines/presets.md
  workloads/virtual-machines/probes.md
  workloads/virtual-machines/startup-scripts.md
  workloads/virtual-machines/unresponsive-nodes.md
  workloads/virtual-machines/virtualized-hardware-configuration.md
  workloads/virtual-machines/vmctl.md
Labels: size/XXL

#182 Fix a small VM formatting error
  creating-virtual-machines/intro.adoc
Labels: size/XS

#185 replace asciibinder link and images with kubevirt
  _images/favicon.ico
  _images/favicon32x32.png
  _templates/page.html.erb
  docs/_images/favicon.ico
  docs/_images/favicon32x32.png
  docs/sitemap.xml
Labels: size/XS

#187 Link virtio win document
  _topic_map.yml
  creating-virtual-machines/virtio-win.adoc
  docs/latest/administration/annotations_and_labels.html
  docs/latest/administration/intro.html
  docs/latest/creating-virtual-machines/guest-operating-system-information.html
  docs/latest/creating-virtual-machines/interfaces-and-networks.html
  docs/latest/creating-virtual-machines/intro.html
  docs/latest/creating-virtual-machines/presets.html
  docs/latest/creating-virtual-machines/startup-scripts.html
  docs/latest/creating-virtual-machines/virtualized-hardware-configuration.html
  docs/latest/using-virtual-machines/graphical-and-console-access.html
  docs/latest/using-virtual-machines/overcommit.html
  docs/sitemap.xml
  workloads/container-disks/README.md
Labels: size/M

#183 Added masquerade documentation
  creating-virtual-machines/interfaces-and-networks.adoc
Labels: size/M
