Repository kubevirt/user-guide, pull requests merged in 2019-04, with the labels that each got.

#224 templates: examples: cnv.io -> kubevirt.io
  templates/common-templates.adoc
Labels: size/M

#220 Document how custom MAC address interacts with misc CNI plugins
  creating-virtual-machines/interfaces-and-networks.adoc
Labels: size/L, topic/network

#225 Document the live migration process
  _topic_map.yml
  administration/live-migration.adoc
Labels: size/L

#227 Document live migration on node-drain
  administration/live-migration.adoc
  administration/node-eviction.adoc
Labels: size/L

#228 Add note about floppy disks being rejected
  creating-virtual-machines/disks-and-volumes.adoc
Labels: size/XS

#230 document lime migration timeouts configuration
  administration/live-migration.adoc
Labels: size/M

#231 Add basic walkthrough for the web interface
  _topic_map.yml
  web-interface/controlling-vms-modules/restart-vm-web.adoc
  web-interface/controlling-vms-modules/start-vm-web.adoc
  web-interface/controlling-vms-modules/stop-vm-web.adoc
  web-interface/managing-disks-modules/vm-create-disk-web.adoc
  web-interface/managing-disks-modules/vm-delete-disk-web.adoc
  web-interface/managing-nics-modules/vm-create-nic-web.adoc
  web-interface/managing-nics-modules/vm-delete-nic-web.adoc
  web-interface/managing-vms-modules/creating-vm-wizard-web.adoc
  web-interface/managing-vms-modules/creating-vm-yaml-web.adoc
  web-interface/managing-vms-modules/delete-vm-web.adoc
  web-interface/managing-vms-modules/editing-vm-web.adoc
  web-interface/managing-vms-modules/editing-vm-yaml-web.adoc
  web-interface/managing-vms-modules/vm-events-web.adoc
  web-interface/resource-modules/cloud-init-fields-web.adoc
  web-interface/resource-modules/networking-wizard-fields-web.adoc
  web-interface/resource-modules/pxebooting.adoc
  web-interface/resource-modules/storage-wizard-fields-web.adoc
  web-interface/resource-modules/template-wizard-fields-web.adoc
  web-interface/resource-modules/vm-actions-web.adoc
  web-interface/resource-modules/vm-wizard-fields-web.adoc
  web-interface/templates-modules/creating-template-wizard-web.adoc
  web-interface/templates-modules/delete-template-web.adoc
  web-interface/templates-modules/editing-template-yaml-web.adoc
  web-interface/vm-consoles-modules/vm-console-web.adoc
  web-interface/vm-consoles-modules/vm-serial-console-web.adoc
  web-interface/vm-consoles-modules/vm-vnc-console-web.adoc
  web-interface/web-interface.adoc
Labels: size/XL

#229 hyperv: sync with the last kubevirt changes
  creating-virtual-machines/guest-operating-system-information.adoc
Labels: size/S

#233 Fix broken link
  administration/intro.adoc
Labels: size/XS

#232 Correct display of notes in web interface walkthrough
  web-interface/controlling-vms-modules/restart-vm-web.adoc
  web-interface/controlling-vms-modules/start-vm-web.adoc
  web-interface/managing-vms-modules/creating-vm-yaml-web.adoc
  web-interface/managing-vms-modules/editing-vm-yaml-web.adoc
  web-interface/resource-modules/pxebooting.adoc
  web-interface/templates-modules/editing-template-yaml-web.adoc
  web-interface/web-interface.adoc
Labels: size/M

#235 Add docs for connecting to RDP via UI
  web-interface/vm-consoles-modules/vm-console-web.adoc
  web-interface/vm-consoles-modules/vm-desktop-viewer-web.adoc
  web-interface/web-interface.adoc
Labels: size/S

#239 Cleaned up masquerade interface type docs
  creating-virtual-machines/interfaces-and-networks.adoc
Labels: size/S

#238 Update Containerized Data Importer version to 1.8
  administration/image-upload.adoc
Labels: size/XS

#236 Added nic binding method to ui docs
  web-interface/managing-nics-modules/vm-create-nic-web.adoc
  web-interface/resource-modules/networking-wizard-fields-web.adoc
Labels: size/XS
