Repository kubevirt/user-guide, pull requests merged in 2019-05, with the labels that each got.

#226 Voluntary shutdown
  _topic_map.yml
  architecture/virtual-machine.adoc
  creating-virtual-machines/run-strategies.adoc
  docs/sitemap.xml
Labels: size/L

#237 Document migration and cancel migration in the UI
  web-interface/controlling-vms-modules/cancel-migrate-vm-web.adoc
  web-interface/controlling-vms-modules/migrate-vm-web.adoc
  web-interface/resource-modules/vm-actions-web.adoc
  web-interface/web-interface.adoc
Labels: size/M

#240 Fix DataVolumes feature gate instructions
  creating-virtual-machines/disks-and-volumes.adoc
Labels: size/XS

#247 Fix copy paste errors in constaineridsk doc
  creating-virtual-machines/disks-and-volumes.adoc
Labels: size/XS

#212 added CPUNodeDiscovery feature gate
  creating-virtual-machines/virtualized-hardware-configuration.adoc
Labels: size/M

#215 Update intro.adoc with delete instructions
  administration/intro.adoc
Labels: size/L

#250 Additional information about KubeVirt updates
  administration/intro.adoc
Labels: size/M

#251 Fixed anchor links (must be lowercase)
  creating-virtual-machines/disks-and-volumes.adoc
Labels: size/S
