Repository kubevirt/user-guide, pull requests merged in 2019-09, with the labels that each got.

#284 monitoring: kubevirt metrics have been renamed
  administration/monitoring.adoc
Labels: size/S

#285 Add Gemfile definition
  Gemfile
Labels: kind/enhancement, size/XS

#286 Add privacy and netlify statement
  welcome/index.adoc
Labels: size/XS

#290 Netlify makefile
  Makefile
Labels: size/S

#293 Remove 'current' branch for avoiding cache issues
  Makefile
Labels: size/XS

#281 Recommend OpenShift SR-IOV operator for deployment
  creating-virtual-machines/interfaces-and-networks.adoc
Labels: size/S

#267 Note and describe the option to disable bridge
  creating-virtual-machines/interfaces-and-networks.adoc
Labels: DCO missing, size/M

#283 web-ui: Deprecate Web UI in favor of openshift/console
  administration/api-validation.adoc
  administration/intro.adoc
  administration/monitoring.adoc
  administration/node-eviction.adoc
  creating-virtual-machines/dedicated-cpu.adoc
  creating-virtual-machines/interfaces-and-networks.adoc
Labels: size/M
