Repository kubevirt/user-guide, pull requests merged in 2019-03, with the labels that each got.

#204 add default cpu model
  creating-virtual-machines/virtualized-hardware-configuration.adoc
Labels: size/S

#213 document how to specify serial number
  creating-virtual-machines/virtualized-hardware-configuration.adoc
Labels: size/XS

#211 replaced generic workload with server workload in templates
  templates/common-templates.adoc
  templates/using-templates.adoc
Labels: size/S

#219 Update CDI version in user guide to latest (1.6.0)
  administration/image-upload.adoc
Labels: size/XS

#217 Fix PersistentVolumeClaim typos
  .aspell.en.pws
  creating-virtual-machines/disks-and-volumes.adoc
Labels: size/S

#216 hyperv: docs for https://github.com/kubevirt/kubevirt/pull/2083
  creating-virtual-machines/guest-operating-system-information.adoc
Labels: size/M

#210 Fix errors in virtio user guide
  creating-virtual-machines/virtio-win.adoc
Labels: size/XS

#209 Don't waste time/resources on ruby document installs.
  .travis.yml
Labels: size/XS

#208 Added note about changed kubevirt account
  administration/intro.adoc
Labels: size/XS

#205 Added documentation about mac address and virt-win
  creating-virtual-machines/interfaces-and-networks.adoc
Labels: size/S

#218 Add instructions regarding virt-handler device plugins
  _topic_map.yml
  administration/device-plugins.adoc
Labels: size/L

#221 changelog: Add up to v0.15.0
  release-notes/changelog.adoc
  release-notes/update_changelog.sh
Labels: size/M

#223 Add release-0.16
  .travis.yml
  _distro_map.yml
Labels: size/XS

#203 Add multus as default pod network example.
  creating-virtual-machines/interfaces-and-networks.adoc
Labels: size/M
