Repository kubevirt/user-guide, pull requests merged in 2019-12, with the labels that each got.

#303 bug fix - multiple lines in release notes
  release-notes/changelog.adoc
  release-notes/update_changelog.sh
Labels: dco-signoff: yes, size/M

#291 Some adjustments to make copy n paste easier
  administration/intro.adoc
Labels: dco-signoff: no, size/S

#301 Added user-guide for virtctl restart
  architecture/virtual-machine.adoc
Labels: dco-signoff: yes, size/S
