Repository kubevirt/user-guide, pull requests merged in 2019-02, with the labels that each got.

#198 Add UEFI/OVMF bootloader documentation
  creating-virtual-machines/virtualized-hardware-configuration.adoc
Labels: size/S

#191 Updated installation to use the operator
  administration/intro.adoc
Labels: do-not-merge/hold, size/M

#195 Extend information for virtio-win usage
  _images/virtio_custom_install_0.png
  _images/virtio_custom_install_1.png
  _images/virtio_custom_install_2.png
  _images/virtio_custom_install_3.png
  _images/virtio_custom_install_4.png
  _images/virtio_custom_install_5.png
  _images/virtio_driver_install_0.png
  _images/virtio_driver_install_1.png
  _images/virtio_driver_install_2.png
  _images/virtio_driver_install_3.png
  creating-virtual-machines/virtio-win.adoc
Labels: size/L

#150 up to date document workloads/templates/vm-creation.md
  templates/using-templates.adoc
Labels: size/L

#202 monitoring: document the VM metrics
  administration/monitoring.adoc
Labels: size/XS

#197 add tablet input device
  creating-virtual-machines/virtualized-hardware-configuration.adoc
Labels: size/M

#177 templates: document the customization
  templates/common-templates.adoc
Labels: size/L

#199 Add user guide section for CPU features.
  creating-virtual-machines/virtualized-hardware-configuration.adoc
Labels: size/M

#200 Add KubeVirt Web UI to the installation section
  administration/intro.adoc
Labels: size/S
