Repository kubevirt/user-guide, pull requests merged in 2020-10, with the labels that each got.

#336 interfaces: drop Genie
  creation/interfaces-and-networks.md
Labels: dco-signoff: yes, lifecycle/stale, size/XS

#344 templates: fix English
  templates/templates.md
Labels: dco-signoff: yes, size/XS

#361 Initial commit for OWNERS file
  OWNERS
Labels: dco-signoff: yes, size/M
