Repository kubevirt/user-guide, pull requests merged in 2020-05, with the labels that each got.

#325 ipv6: explain how to configure IPv6 support for masquerade
  creation/interfaces-and-networks.md
Labels: dco-signoff: yes, size/M

#326 Explicitly set required permissions for containerDisk
  creation/disks-and-volumes.md
Labels: dco-signoff: yes, size/S

#329 Added documentation for how to rename a VM
  usage/life-cycle.md
Labels: dco-signoff: yes, size/XS

#330 Storage and formatting fixes
  architecture.md
  creation/creating-virtual-machines.md
  creation/devices.md
  creation/disks-and-volumes.md
  installation/image-upload.md
  installation/node-eviction.md
  installation/virtctl.md
Labels: dco-signoff: yes, size/L
