Repository kubevirt/user-guide, pull requests merged in 2020-11, with the labels that each got.

#365 kubectl autoscale works with VMIRS a long time now
  usage/virtual-machine-replica-set.md
Labels: dco-signoff: yes, size/XS

#338 networks: masquerade: default is forward all ports
  creation/interfaces-and-networks.md
Labels: dco-signoff: yes, lifecycle/rotten, size/XS

#363 Fix dhcpOptions feature description
  creation/interfaces-and-networks.md
Labels: dco-signoff: yes, size/XS

#366 Fix manifest file name
  installation/image-upload.md
Labels: dco-signoff: yes, size/XS

#368 Document the configuration and assignment of Host Devices
  creation/host-devices.md
Labels: dco-signoff: no, size/L

#340 correct delete comment
  architecture.md
Labels: dco-signoff: no, lifecycle/rotten, size/XS

#356 Create Getting Started page
  README.md
  _sidebar.md
  appendix/appendix.md
  appendix/contributing.md
Labels: dco-signoff: no, size/M

#346 Minor typo correction & change env var to be consistent with updating doc
  installation/installation.md
Labels: dco-signoff: no, lifecycle/stale, size/S

#364 Macvtap user guide
  creation/interfaces-and-networks.md
Labels: dco-signoff: yes, size/L
