Repository kubevirt/user-guide, pull requests merged in 2020-02, with the labels that each got.

#305 Added user-guide for dedicated cpu for QEMU Emulator
  creating-virtual-machines/dedicated-cpu.adoc
Labels: dco-signoff: yes, size/S

#307 State PVC requirements
  administration/live-migration.adoc
Labels: dco-signoff: yes, size/XS

#308 Update changelog
  release-notes/changelog.adoc
Labels: dco-signoff: yes, size/S

#312 update image upload doc to be more DataVolume centric
  administration/image-upload.adoc
Labels: dco-signoff: yes, size/M
