Repository kubevirt/user-guide, pull requests merged in 2020-12, with the labels that each got.

#374 [WIP] Fixed various typos in documentation
  architecture.md
  creation/run-strategies.md
Labels: dco-signoff: yes, do-not-merge/work-in-progress, size/XS

#333 remove references to kubevirt-config ConfigMap
  creation/dedicated-cpu.md
  creation/devices.md
  creation/disks-and-volumes.md
  creation/guest-operating-system-information.md
  creation/interfaces-and-networks.md
  installation/authorization.md
  installation/installation.md
  installation/live-migration.md
  installation/node-eviction.md
  usage/overcommit.md
Labels: dco-signoff: yes, size/L

#373 user-guide, sriov: note about dedicatedCpuPlacement
  creation/interfaces-and-networks.md
Labels: dco-signoff: yes, size/XS
