Repository kubevirt/user-guide, pull requests merged in 2020-06, with the labels that each got.

#328 Update IPv6 addresses
  creation/interfaces-and-networks.md
Labels: dco-signoff: yes, size/XS

#332 ipv6, cloud-init: configure static ipv6 via networkData
  creation/interfaces-and-networks.md
Labels: dco-signoff: yes, size/S

#320 Fix some typos
  installation/live-migration.md
Labels: dco-signoff: yes, lifecycle/stale, size/M
