Repository kubevirt/user-guide, pull requests merged in 2020-09, with the labels that each got.

#315 Add Guest agent usage documentation
  _sidebar.md
  usage/guest-agent.md
Labels: dco-signoff: yes, size/L

#353 Update live-migration.md
  installation/live-migration.md
Labels: dco-signoff: no, size/XS

#355 fix typo
  creation/disks-and-volumes.md
Labels: dco-signoff: yes, size/XS

#358 Dual stack probes limitations
  creation/probes.md
Labels: dco-signoff: yes, size/S
