Repository kubevirt/user-guide, pull requests merged in 2021-08, with the labels that each got.

#470 Added reviewers, approver
  OWNERS
Labels: size/XS, dco-signoff: yes, lgtm

#462 Updated Links
  docs/virtual_machines/windows_virtio_drivers.md
Labels: size/S, dco-signoff: yes, approved, lgtm

#472 added empty array to network policy
  docs/virtual_machines/networkpolicy.md
Labels: size/XS, dco-signoff: yes, approved, lgtm

#475 interfaces-and-networks: Add a security section with spoof-checking
  docs/virtual_machines/interfaces_and_networks.md
Labels: size/M, dco-signoff: yes, approved, lgtm

#468 document macvlan limitation for live-migration
  docs/virtual_machines/interfaces_and_networks.md
Labels: size/XS, dco-signoff: yes, approved, lgtm

#474 Fix broken architecture graph link
  docs/architecture.md
Labels: size/XS, dco-signoff: yes, approved, lgtm

#480 OWNERS: make Ashley an emeritus approver
  OWNERS
Labels: size/XS, dco-signoff: yes, approved, lgtm
