Repository kubevirt/user-guide, pull requests merged in 2021-04, with the labels that each got.

#421 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#422 Simple link fix in README
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#427 host-devices.md: general text cleanup
  docs/virtual_machines/host-devices.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#428 Document cpuAllocationRatio
  docs/operations/node_overcommit.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#429 Fix markdown formatting in CPU Manager subsection in Dedicated CPU Resources
  docs/virtual_machines/dedicated_cpu_resources.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#425 Fix links
  docs/.pages
  docs/index.md
  docs/welcome.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#434 fixing spelling test typos
  docs/operations/node_overcommit.md
  docs/virtual_machines/host-devices.md
  docs/virtual_machines/virtual_hardware.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#435 Fix link
  CONTRIBUTING.md
Labels: dco-signoff: yes, lgtm, size/XS

#437 added steps to avoid using --uploadproxy-url for issue 334
  docs/operations/containerized_data_importer.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#436 Fixes https://github.com/kubevirt/kubevirt/issues/5395
  docs/virtual_machines/run_strategies.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#438 Added certificate information to cdi
  docs/operations/containerized_data_importer.md
Labels: approved, dco-signoff: yes, lgtm, size/L
