Repository kubevirt/user-guide, pull requests merged in 2021-05, with the labels that each got.

#439 Add description of VirtualMachine printableStatus field
  docs/architecture.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#440 Fix command adding entry to hosts file
  docs/operations/containerized_data_importer.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#441 Build img consolidation and streamline
  .gitignore
  Gemfile.lock
  Makefile
  _config/src/Gemfile
Labels: approved, dco-signoff: yes, lgtm, size/L

#442 [FIX] Update virtctl_client_tool.md
  docs/operations/virtctl_client_tool.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#448 Remove duplicated eviction info
  docs/operations/.pages
  docs/operations/virtualmachineinstance_node_eviction.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#444 Added Note to enable Feature Gate HostDisk
  docs/virtual_machines/disks_and_volumes.md
Labels: approved, dco-signoff: yes, lgtm, size/XS
