Repository kubevirt/user-guide, pull requests merged in 2021-09, with the labels that each got.

#481 Moving codificat/hroyrh to emeritus_approvers...end of an era
  OWNERS
Labels: size/XS, dco-signoff: yes, approved, lgtm

#479 Fix broken markdown links
  README.md
  docs/architecture.md
  docs/index.md
  docs/operations/installation.md
  docs/operations/node_overcommit.md
  docs/virtual_machines/accessing_virtual_machines.md
  docs/virtual_machines/disks_and_volumes.md
  docs/virtual_machines/guest_agent_information.md
  docs/virtual_machines/guest_operating_system_information.md
  docs/virtual_machines/replicaset.md
  docs/virtual_machines/startup_scripts.md
  docs/virtual_machines/templates.md
  docs/virtual_machines/virtual_machine_instances.md
  docs/virtual_machines/windows_virtio_drivers.md
Labels: size/M, dco-signoff: yes, approved, lgtm

#483 Updated the Try it Out! bullet point
  docs/index.md
Labels: size/XS, dco-signoff: yes, approved, lgtm

#485 Fix snippet rendering of ptp-mac example
  docs/virtual_machines/interfaces_and_networks.md
Labels: size/M, dco-signoff: yes, approved, lgtm

#469 Improve documentation for Sysprep API
  docs/virtual_machines/startup_scripts.md
Labels: size/XS, dco-signoff: yes, approved, lgtm

#488 Adjustments to Makefile
  Makefile
Labels: size/M, dco-signoff: yes, approved, lgtm

#487 Add snapshot and hotplug documentation
  docs/operations/.pages
  docs/operations/hotplug_volumes.md
  docs/operations/snapshot_restore_api.md
Labels: size/L, dco-signoff: yes, approved, lgtm

#484 Imporve sysprep doc
  docs/virtual_machines/startup_scripts.md
Labels: size/L, dco-signoff: yes, approved, lgtm

#457 Document basic NUMA support
  docs/virtual_machines/.pages
  docs/virtual_machines/numa.md
Labels: size/M, dco-signoff: yes, approved, lgtm
