Repository kubevirt/user-guide, pull requests merged in 2021-03, with the labels that each got.

#391 Makefile refactoring
  .gitignore
  Makefile
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#399 Updated Missing Link
  docs/virtual_machines/virtual_machine_instances.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#385 Update outdated documentation for common-templates
  docs/virtual_machines/templates.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#402 Fix spelling
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#400 Document KubeVirt VMI update automation
  docs/operations/updating_and_deletion.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#401 Update script to allow version args and change how markdown is popula…
  docs/latest_release_notes.md
  update_changelog.sh
Labels: approved, dco-signoff: yes, lgtm, size/L

#403 Fix to Gemfile.lock read-only warning
  Makefile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#404 Fix non-ascii characters
  docs/architecture.md
  docs/assets/check.png
  docs/assets/ellipsis.png
  docs/assets/pause.png
  docs/assets/play.png
  docs/operations/api_validation.md
  docs/operations/authorization.md
  docs/operations/component_monitoring.md
  docs/operations/containerized_data_importer.md
  docs/operations/live_migration.md
  docs/operations/node_assignment.md
  docs/operations/node_maintenance.md
  docs/operations/node_overcommit.md
  docs/operations/unresponsive_nodes.md
  docs/operations/updating_and_deletion.md
  docs/operations/virtualmachineinstance_node_eviction.md
  docs/virtual_machines/dedicated_cpu_resources.md
  docs/virtual_machines/disks_and_volumes.md
  docs/virtual_machines/interfaces_and_networks.md
  docs/virtual_machines/networkpolicy.md
  docs/virtual_machines/presets.md
  docs/virtual_machines/run_strategies.md
  docs/virtual_machines/startup_scripts.md
  docs/virtual_machines/templates.md
  docs/virtual_machines/virtual_hardware.md
  docs/virtual_machines/virtual_machine_instances.md
  docs/web_console.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#408 disks: configmap: clarify sentence about update
  docs/virtual_machines/disks_and_volumes.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#407 Minor markdown rendering fixes
  docs/operations/updating_and_deletion.md
  docs/virtual_machines/host-devices.md
  docs/virtual_machines/startup_scripts.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#406 Fix broken links plus supporting fixes
  Rakefile
  docs/assets/actions.png
  docs/operations/node_overcommit.md
  docs/virtual_machines/accessing_virtual_machines.md
  docs/virtual_machines/templates.md
  docs/web_console.md
  mkdocs.yml
Labels: approved, dco-signoff: yes, lgtm, size/L

#410 fixing favicon
  mkdocs.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#413 Fix bullet lists in contributions page
  docs/appendix/contributing.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#386 update node-labeller documentation
  docs/virtual_machines/virtual_hardware.md
Labels: approved, dco-signoff: yes, lgtm, size/M
