Repository kubevirt/user-guide, pull requests merged in 2021-07, with the labels that each got.

#456 Document migrations without TLS
  docs/operations/live_migration.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#458 Document ARM developer build installation
  docs/operations/installation.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#449 Fix Architecture Section
  docs/architecture.md
  docs/assets/architecture-simple.png
  docs/assets/architecture.png
Labels: approved, dco-signoff: yes, lgtm, size/L

#461 Fix spelling error
  docs/virtual_machines/host-devices.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#465 Document live-migration reserved ports
  docs/operations/live_migration.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#466 Add user-guide for VMI with Istio
  docs/virtual_machines/.pages
  docs/virtual_machines/istio_service_mesh.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#467 add user guide for patch and flag customization options
  docs/operations/customize_components.md
Labels: approved, dco-signoff: yes, lgtm, size/M
