Repository kubevirt/user-guide, pull requests merged in 2021-02, with the labels that each got.

#379 fix typo
  creation/cloud-init.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#380 Document watchdog usage
  creation/probes.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#381 Fix typo in architecture.md
  architecture.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#382 Add documentation for vnc proxy-only mode
  usage/graphical-and-console-access.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#383 added information for k3OS installation
  installation/installation.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#390 Spelling fix in CDI documentation
  docs/operations/containerized_data_importer.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#388 Fixed issue with userguide image name caused by build target refactor
  Makefile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#389 Fix failing links in content
  docs/architecture.md
  docs/virtual_machines/.pages
  docs/virtual_machines/disks_and_volumes.md
  docs/virtual_machines/guest_operating_system_information.md
  docs/virtual_machines/replicaset.md
  docs/virtual_machines/service_objects.md
  docs/virtual_machines/startup_scripts.md
  docs/virtual_machines/templates.md
  docs/virtual_machines/virtual_machine_instances.md
  docs/virtual_machines/windows_virtio_drivers.md
  docs/welcome.md
  mkdocs.yml
Labels: approved, dco-signoff: yes, lgtm, size/M

#392 docs/architecture.md: typo fixes
  docs/architecture.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#395 Remove vmctl documentation
  docs/operations/.pages
  docs/operations/vmctl.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#394 Access credential documentation
  docs/virtual_machines/.pages
  docs/virtual_machines/accessing_virtual_machines.md
  docs/virtual_machines/graphical_and_console_access.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#396 host devices: case consistency
  docs/virtual_machines/host-devices.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#384 Add documentation for Sysprep API support
  docs/virtual_machines/startup_scripts.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#393 fixed broken links
  docs/welcome.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#397 fix cdi cr download broken link
  docs/operations/containerized_data_importer.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#387 Add paragraph with descheduler annotation
  docs/operations/node_assignment.md
Labels: approved, dco-signoff: yes, lgtm, size/S
