Repository kubevirt/user-guide, pull requests merged in 2022-02, with the labels that each got.

#520 Fix cpu resource request and limit (#519)
  docs/virtual_machines/virtual_hardware.md
Labels: size/XS, dco-signoff: yes, approved, lgtm

#513 update vmi preset version to v1
  docs/virtual_machines/presets.md
Labels: size/M, dco-signoff: yes, approved, lgtm

#518 Document the configuration of mediated devices
  docs/operations/.pages
  docs/operations/mediated_devices_configuration.md
  docs/virtual_machines/host-devices.md
Labels: size/L, dco-signoff: yes, approved, lgtm
