Repository kubevirt/user-guide, pull requests merged in 2022-03, with the labels that each got.

#523 add docs for shareable option
  docs/virtual_machines/disks_and_volumes.md
Labels: size/L, dco-signoff: yes, approved, lgtm

#524 network, macvtap: fix markdown
  docs/virtual_machines/interfaces_and_networks.md
Labels: size/XS, dco-signoff: yes, approved, lgtm

#514 Correct the spacing for device tagging snippet
  docs/virtual_machines/startup_scripts.md
Labels: size/XS, dco-signoff: yes, approved, lgtm

#522 migration: how to initiate and cancel migrations using virtctl
  docs/operations/live_migration.md
  docs/operations/virtctl_client_tool.md
Labels: size/S, dco-signoff: yes, approved, lgtm, ok-to-test

#525 Fixed feature gate requirement for DV
  docs/virtual_machines/disks_and_volumes.md
Labels: size/XS, dco-signoff: yes, approved, lgtm
