Repository kubevirt/user-guide, pull requests merged in 2022-09, with the labels that each got.

#549 VirtualMachineExport documentation
  docs/operations/export_api.md
Labels: size/L, dco-signoff: yes, approved, lgtm

#575 Update virtual_hardware.md
  docs/virtual_machines/virtual_hardware.md
Labels: size/S, dco-signoff: yes, approved, lgtm

#565 Add user-guide for Migration Policies
  docs/operations/.pages
  docs/operations/migration_policies.md
Labels: size/L, dco-signoff: yes, approved, lgtm

#573 improve kubevirt tekton tasks documentation
  docs/virtual_machines/tekton_tasks.md
Labels: size/XS, dco-signoff: yes, approved, lgtm

#564 Add user-guide for clone API
  docs/operations/.pages
  docs/operations/clone_api.md
Labels: size/L, dco-signoff: yes, approved, lgtm

#580 fix typo in macvtap config
  docs/virtual_machines/interfaces_and_networks.md
Labels: size/XS, dco-signoff: yes, approved, lgtm, ok-to-test

#584 Fix list formatting in rendered docs (Application Layout)
  docs/architecture.md
Labels: size/XS, dco-signoff: yes, approved, lgtm, ok-to-test

#585 docs, probes: Add guest-agent exec probes documentation
  docs/virtual_machines/liveness_and_readiness_probes.md
Labels: size/L, dco-signoff: yes, approved, lgtm, ok-to-test

#589 passt: fix sysctl file_max to file-max
  docs/virtual_machines/interfaces_and_networks.md
Labels: size/XS, dco-signoff: yes, approved, lgtm

#586 Updating release notes for v0.57.0
  docs/release_notes.md
Labels: size/S, dco-signoff: yes, approved, lgtm

#592 operations: add missing pages to the index
  docs/operations/.pages
Labels: size/XS, dco-signoff: yes, approved, lgtm

#590 Update export API documentation to cover virtctl integration
  docs/operations/export_api.md
  docs/operations/memory_dump.md
Labels: size/L, dco-signoff: yes, approved, lgtm

#597 Update instancetype docs for version v1alpha2
  docs/virtual_machines/instancetypes.md
Labels: size/M, dco-signoff: yes, approved, lgtm
