Repository kubevirt/user-guide, pull requests merged in 2022-01, with the labels that each got.

#503 Fix virtio-containerdisk references
  docs/virtual_machines/startup_scripts.md
  docs/virtual_machines/windows_virtio_drivers.md
Labels: size/S, dco-signoff: yes, approved, lgtm

#509 add limitations when memfd is supported
  docs/virtual_machines/virtual_hardware.md
Labels: approved, lgtm, ok-to-test

#504 guest_agent_information: Add info about vmi status infoSource
  docs/virtual_machines/guest_agent_information.md
Labels: size/M, dco-signoff: yes, approved, lgtm

#506 Fix doc for batchEviction{Size,Interval}
  docs/operations/updating_and_deletion.md
Labels: size/XS, dco-signoff: yes, approved, lgtm, ok-to-test

#511 docs, network: clarify MAC setting on pod iface requires multus
  docs/virtual_machines/interfaces_and_networks.md
Labels: size/XS, dco-signoff: yes, approved, lgtm

#510 migration: add network documentation
  docs/operations/live_migration.md
Labels: size/L, dco-signoff: yes, approved, lgtm
