Repository kubevirt/user-guide, pull requests merged in 2022-11, with the labels that each got.

#607 Linked kubevirt labs to docs
  docs/index.md
Labels: size/S, dco-signoff: yes, approved, lgtm, ok-to-test

#605 added quickstart guides to ToC
  docs/.pages
  docs/quickstarts.md
Labels: size/S, dco-signoff: yes, approved, lgtm, needs-ok-to-test

#613 Adding VSOCK
  docs/virtual_machines/.pages
  docs/virtual_machines/vsock.md
Labels: size/M, dco-signoff: yes, approved, lgtm, needs-ok-to-test

#616 Updates for new netlify image
  netlify.toml
Labels: size/XS, dco-signoff: yes, approved, lgtm

#617 Update Makefile to use latest netlify python ver
  Makefile
Labels: size/XS, dco-signoff: yes, lgtm

#620 Resetting to opt build repo path
  netlify.toml
Labels: size/XS, dco-signoff: yes, lgtm

#615 virtiofs, hostpath: Add an example for using hostpath in VMs.
  docs/virtual_machines/disks_and_volumes.md
Labels: size/L, dco-signoff: yes, approved, lgtm, needs-ok-to-test

#622 Fix livenessProbe typo in example
  docs/virtual_machines/liveness_and_readiness_probes.md
Labels: size/XS, dco-signoff: yes, approved, lgtm, ok-to-test

#619 passt: Remove note about extra memory when using passt
  docs/virtual_machines/interfaces_and_networks.md
Labels: size/XS, dco-signoff: yes, approved, lgtm

#624 Change to just python3 not a point release
  Makefile
Labels: approved, lgtm

#618 apparmor: Recommend removing libvirt package
  docs/operations/installation.md
Labels: size/S, dco-signoff: yes, approved, lgtm

#600 Disk sharing example PVC should use RWX access mode
  docs/virtual_machines/disks_and_volumes.md
Labels: size/XS, dco-signoff: yes, approved, lgtm

#595 installation docs: add minimum container-selinux version
  docs/operations/installation.md
Labels: size/XS, dco-signoff: yes, approved, lgtm

#598 instancetype: Update versioning section
  docs/virtual_machines/instancetypes.md
Labels: size/S, dco-signoff: yes, approved, lgtm

#625 Removing ornamental which statement due to missing in container
  Makefile
Labels: size/XS, dco-signoff: yes, approved, lgtm
