Repository kubevirt/user-guide, pull requests merged in 2022-08, with the labels that each got.

#552 Update snapshot_restore docs to mention support for only v1 apis
  docs/operations/snapshot_restore_api.md
Labels: size/XS, dco-signoff: yes, approved, lgtm, ok-to-test

#567 Add missing Secure Boot documentation
  docs/virtual_machines/virtual_hardware.md
Labels: size/XS, dco-signoff: yes, approved, lgtm

#568 Renaming 'Latest release notes' to 'KubeVirt release notes'
  docs/.pages
  docs/release_notes.md
  update_changelog.sh
Labels: size/S, dco-signoff: yes, approved, lgtm

#550 Move danielBelenky to emeritus_approvers
  OWNERS
Labels: size/XS, dco-signoff: yes, approved, lgtm

#570 passt documentation
  docs/virtual_machines/interfaces_and_networks.md
  docs/virtual_machines/istio_service_mesh.md
Labels: size/M, dco-signoff: yes, approved, lgtm

#571 Katacoda is dead. Sad times.
  docs/index.md
Labels: size/XS, dco-signoff: yes, approved, lgtm, ok-to-test

#563 add delete virt-operator-validator webhook guide
  docs/operations/updating_and_deletion.md
Labels: size/XS, dco-signoff: yes, approved, lgtm, ok-to-test

#566 Update memory dump doc with new feature improvements
  docs/operations/memory_dump.md
Labels: size/M, dco-signoff: yes, approved, lgtm

#569 Add instancetypes documentation
  docs/virtual_machines/.pages
  docs/virtual_machines/instancetypes.md
  docs/virtual_machines/virtual_machine_instances.md
Labels: size/L, dco-signoff: yes, approved, lgtm

#560 multi queue: Introduce queueCount field
  docs/virtual_machines/interfaces_and_networks.md
Labels: size/XS, dco-signoff: yes, approved, lgtm

#577 Update some of the hotplug documentation
  docs/operations/hotplug_volumes.md
Labels: size/XS, dco-signoff: yes, approved, lgtm

#540 life-cycle: Add documentation about force stop
  docs/architecture.md
  docs/virtual_machines/lifecycle.md
Labels: size/S, dco-signoff: yes, approved, lgtm

#559 Adjust on the get of the latest CDI tag version
  docs/operations/containerized_data_importer.md
Labels: size/XS, dco-signoff: yes, approved, lgtm, ok-to-test

#578 Update the cloudInitNoCloud userdata example
  docs/virtual_machines/startup_scripts.md
Labels: size/XS, dco-signoff: yes, approved, lgtm, ok-to-test
