Repository kubevirt/user-guide, pull requests merged in 2022-06, with the labels that each got.

#545 docs: Fix typo in architecture and vmi
  docs/architecture.md
  docs/virtual_machines/virtual_machine_instances.md
Labels: size/S, dco-signoff: yes, approved, lgtm, ok-to-test

#544 Add documentation for memory dump command
  docs/operations/memory_dump.md
Labels: size/L, dco-signoff: yes, approved, lgtm

#546 Updating latest_release_notes from 0.38.1 to 0.54.0
  docs/latest_release_notes.md
Labels: size/XL, dco-signoff: yes, approved, lgtm, ok-to-test

#551 docs, install guide: point to latest release rather than v0.35.0
  docs/operations/installation.md
Labels: size/XS, dco-signoff: yes, approved, lgtm
