Repository kubevirt/user-guide, pull requests merged in 2022-10, with the labels that each got.

#583 docs, probes: fix readiness and liveness examples
  docs/virtual_machines/liveness_and_readiness_probes.md
Labels: size/L, dco-signoff: yes, approved, lgtm, ok-to-test

#581 Mark VirtualMachineInstancePresets as deprecated
  docs/virtual_machines/presets.md
Labels: size/XS, dco-signoff: yes, approved, lgtm

#602 Adding v0.58.0 release notes
  docs/release_notes.md
Labels: size/S, dco-signoff: yes, approved, lgtm

#599 Rework Accessing Virtual Machines section
  docs/virtual_machines/accessing_virtual_machines.md
Labels: size/L, dco-signoff: yes, approved, lgtm

#604 Fix headers and yaml formatting in NetworkPolicy
  docs/virtual_machines/networkpolicy.md
Labels: size/M, dco-signoff: yes, approved, lgtm, ok-to-test

#591 add example how to enable deployTektonTaskResources feature gate in hco cr
  docs/virtual_machines/tekton_tasks.md
Labels: size/XS, dco-signoff: yes, approved, lgtm

#610 Change references to v1alpha3 to v1
  docs/architecture.md
  docs/operations/component_monitoring.md
  docs/operations/containerized_data_importer.md
  docs/operations/customize_components.md
  docs/operations/live_migration.md
  docs/operations/node_assignment.md
  docs/operations/node_maintenance.md
  docs/operations/node_overcommit.md
  docs/operations/updating_and_deletion.md
  docs/virtual_machines/dedicated_cpu_resources.md
  docs/virtual_machines/disks_and_volumes.md
  docs/virtual_machines/dns.md
  docs/virtual_machines/guest_agent_information.md
  docs/virtual_machines/guest_operating_system_information.md
  docs/virtual_machines/interfaces_and_networks.md
  docs/virtual_machines/replicaset.md
  docs/virtual_machines/run_strategies.md
  docs/virtual_machines/service_objects.md
  docs/virtual_machines/startup_scripts.md
  docs/virtual_machines/templates.md
  docs/virtual_machines/virtual_hardware.md
  docs/virtual_machines/virtual_machine_instances.md
Labels: size/L, dco-signoff: yes, approved, lgtm, ok-to-test

#611 Adds virtio-fs user guide
  docs/virtual_machines/disks_and_volumes.md
Labels: size/M, dco-signoff: yes, approved, lgtm, ok-to-test

#609 Update list of supported CRI implementations
  docs/operations/installation.md
Labels: size/XS, dco-signoff: yes, approved, lgtm

#612 Document the support status of AppArmor
  docs/operations/installation.md
Labels: size/M, dco-signoff: yes, approved, lgtm
