Repository kubevirt/user-guide, pull requests merged in 2022-04, with the labels that each got.

#527 Update contributing.md
  docs/appendix/contributing.md
Labels: size/XS, dco-signoff: yes, approved, lgtm, ok-to-test

#528 docs, network: document bridge interface invalid CNIs
  docs/virtual_machines/interfaces_and_networks.md
Labels: size/S, dco-signoff: yes, approved, lgtm

#529 [Kernel boot]: fix doc - kernel args without image is disallowed
  docs/virtual_machines/boot_from_external_source.md
Labels: size/XS, dco-signoff: yes, approved, lgtm

#531 IPv6 single stack: adding documentation.
  docs/virtual_machines/interfaces_and_networks.md
Labels: size/S, dco-signoff: yes, approved, lgtm

#532 Add explaination about serviceMonitorNamespace field of kubevirtCR
  docs/operations/component_monitoring.md
Labels: size/XS, dco-signoff: yes, approved, lgtm

#530 Bump docs.openshift links to 4.10
  docs/operations/containerized_data_importer.md
  docs/operations/installation.md
  docs/virtual_machines/dedicated_cpu_resources.md
  docs/virtual_machines/templates.md
  docs/virtual_machines/windows_virtio_drivers.md
  docs/web_console.md
Labels: size/S, dco-signoff: yes, approved, lgtm, needs-ok-to-test

#533 Add documentation for defining verbosity levels
  docs/operations/.pages
  docs/operations/debug.md
Labels: size/M, dco-signoff: yes, approved, lgtm

#536 network: fix markdown for invalid CNIs
  docs/virtual_machines/interfaces_and_networks.md
Labels: size/XS, dco-signoff: yes, approved, lgtm

#534 update kubernets version dependency
  docs/operations/installation.md
Labels: size/XS, dco-signoff: yes, approved, lgtm

#535 Fix example in kubevirtCR to set obsoleteCPUModels with correct values
  docs/virtual_machines/virtual_hardware.md
Labels: size/XS, dco-signoff: yes, approved, lgtm
