Repository kubevirt/user-guide, pull requests merged in 2023-06, with the labels that each got.

#673 Virtiofs, configvolumes: Add how to share configvolumes with virtiofs.
  docs/virtual_machines/disks_and_volumes.md
Labels: size/L, dco-signoff: yes, approved, lgtm

#685 hotplug-interfaces: Use VirtualMachine in the example
  docs/operations/hotplug_interfaces.md
Labels: size/M, dco-signoff: yes, approved, lgtm

#686 hotplug-interfaces: Update the limitation section with reserved ifaces
  docs/operations/hotplug_interfaces.md
Labels: size/S, dco-signoff: yes, approved, lgtm

#688 Add documentation for ksm
  docs/operations/.pages
  docs/operations/ksm.md
Labels: size/M, dco-signoff: yes, approved, lgtm

#669 Add ignition documentation
  docs/virtual_machines/disks_and_volumes.md
  docs/virtual_machines/startup_scripts.md
Labels: size/L, dco-signoff: yes, approved, lgtm, ok-to-test

#667 Re-arrange contributor guide
  docs/contributing.md
Labels: size/S, dco-signoff: yes, approved, lgtm

#689 hotplug interface: allowed only on VMs
  docs/operations/hotplug_interfaces.md
Labels: size/S, dco-signoff: yes, approved, lgtm

#662 Update debug.md
  docs/operations/debug.md
  docs/operations/live_migration.md
Labels: size/XS, dco-signoff: yes, approved, lgtm, ok-to-test

#691 Update disks_and_volumes.md (typo)
  docs/virtual_machines/disks_and_volumes.md
Labels: size/XS, dco-signoff: yes, approved, lgtm, ok-to-test
