Repository kubevirt/user-guide, pull requests merged in 2023-03, with the labels that each got.

#651 Update virtctl_client_tool.md
  docs/operations/virtctl_client_tool.md
Labels: size/XS, dco-signoff: yes, approved, lgtm

#646 VirtualMachinePool Documentation
  docs/virtual_machines/.pages
  docs/virtual_machines/pool.md
Labels: size/L, dco-signoff: yes, approved, lgtm, ok-to-test

#650 Introduce horizontal menu
  docs/.pages
  docs/appendix/.pages
  docs/architecture.md
  docs/contributing.md
  docs/index.md
  docs/quickstarts.md
  docs/release_notes.md
  docs/stylesheets/extra.css
  docs/web_console.md
  mkdocs.yml
Labels: size/M, dco-signoff: yes, approved, lgtm

#656 Fixed broken links in user-guide
  README.md
  docs/index.md
  docs/operations/authorization.md
  docs/operations/clone_api.md
  docs/virtual_machines/startup_scripts.md
  docs/virtual_machines/tekton_tasks.md
Labels: size/S, dco-signoff: yes, approved, lgtm, needs-ok-to-test

#652 hotplug nic: document new feature
  docs/operations/.pages
  docs/operations/hotplug_interfaces.md
Labels: size/L, dco-signoff: yes, approved, lgtm

#658 Added Kubevirt v0.59.0 release notes
  docs/release_notes.md
Labels: size/L, dco-signoff: yes, approved, lgtm, needs-ok-to-test

#653 Remove Web Console documentation
  docs/.pages
  docs/web_console.md
Labels: size/XL, dco-signoff: yes, approved, lgtm

#649 disks-and-volumes: remove reference to floppy
  docs/virtual_machines/disks_and_volumes.md
Labels: size/M, dco-signoff: yes, approved, lgtm

#663 hotplug NIC: Rename virtctl addinterface arguments names
  docs/operations/hotplug_interfaces.md
Labels: size/XS, dco-signoff: yes, approved, lgtm

#664 Document hotplug network interfaces using live migration
  docs/operations/hotplug_interfaces.md
Labels: size/S, dco-signoff: yes, approved, lgtm

#668 Example of on the fly PR
  docs/index.md
Labels: size/XS, dco-signoff: yes, approved, lgtm
