Repository kubevirt/user-guide, pull requests merged in 2023-01, with the labels that each got.

#626 Add the need to stop VM before restore
  docs/operations/snapshot_restore_api.md
Labels: size/XS, dco-signoff: yes, approved, lgtm

#630 Update memory dump command with download options
  docs/operations/memory_dump.md
Labels: size/M, dco-signoff: yes, approved, lgtm

#631 Fixed ClusterInstancetype spelling error in instancetypes
  docs/virtual_machines/instancetypes.md
Labels: size/XS, dco-signoff: yes, approved, lgtm, ok-to-test

#632 Increasing nav depth and disabling sticky_nav
  mkdocs.yml
Labels: size/XS, dco-signoff: yes, approved, lgtm

#635 Add client passthrough documentation
  docs/operations/.pages
  docs/operations/client_passthrough.md
Labels: size/M, dco-signoff: yes, approved, lgtm

#636 client-passthrough: Improve docs further
  docs/operations/client_passthrough.md
Labels: size/S, dco-signoff: yes, approved, lgtm

#633 Switch to Material theme
  Makefile
  docs/stylesheets/extra.css
  mkdocs.yml
  netlify.toml
Labels: size/M, dco-signoff: yes, approved, lgtm
