Repository kubevirt/user-guide, pull requests merged in 2023-09, with the labels that each got.

#709 Adding important community links to contributor page
  docs/contributing.md
Labels: size/S, dco-signoff: yes, approved, lgtm

#713 Document memory and CPU requests and limits
  docs/virtual_machines/.pages
  docs/virtual_machines/resources_requests_and_limits.md
Labels: size/M, dco-signoff: yes, approved, lgtm

#716 operation: add support of Arm64 platform in the installation page
  docs/operations/installation.md
Labels: size/XS, dco-signoff: yes, approved, lgtm

#720 Export API: Update documentation with new vmexport flags
  docs/operations/export_api.md
Labels: size/S, dco-signoff: yes, approved, lgtm
