Repository kubevirt/user-guide, pull requests merged in 2023-11, with the labels that each got.

#727 Adding the v1.1.0 release notes for Nov 7
  docs/release_notes.md
Labels: size/M, dco-signoff: yes, approved, lgtm

#729 Dynamic Networks: Document new API for hotplug/unplug
  docs/operations/hotplug_interfaces.md
Labels: size/L, dco-signoff: yes, approved, lgtm

#732 ✏️ Fix typo in live_migration page
  docs/operations/live_migration.md
Labels: size/XS, dco-signoff: yes, approved, lgtm, needs-ok-to-test

#718 Add USB pass through documentation
  docs/virtual_machines/host-devices.md
Labels: size/M, dco-signoff: yes, approved, lgtm

#724 Fix ordered list in update doc
  docs/operations/updating_and_deletion.md
Labels: size/S, dco-signoff: yes, approved, lgtm, needs-ok-to-test

#702 update metric name
  docs/operations/component_monitoring.md
Labels: size/XS, dco-signoff: yes, approved, lgtm

#731 Refine dynamic networking doc phrasing and formating
  docs/operations/hotplug_interfaces.md
Labels: size/M, dco-signoff: yes, approved, lgtm

#707 Update description for VirtualMachineClone phase
  docs/operations/clone_api.md
Labels: size/S, dco-signoff: yes, approved, lgtm, needs-ok-to-test

#735 Document how to use the error policy
  docs/virtual_machines/disks_and_volumes.md
Labels: size/S, dco-signoff: yes, approved, lgtm

#736 IsolateEmulatorThread with full-pcpus-only
  docs/virtual_machines/dedicated_cpu_resources.md
Labels: size/S, dco-signoff: yes, approved, lgtm

#739 network: masquerade improvements
  docs/virtual_machines/interfaces_and_networks.md
Labels: size/S, dco-signoff: yes, approved, lgtm

#740 cloneAPI: add how to use template label and annotation filters
  docs/operations/clone_api.md
Labels: size/S, dco-signoff: yes, approved, lgtm, needs-ok-to-test

#725 Add debugging virt stack
  docs/debug_virt_stack/kubevirt-demo-debug-qemu-strace.png
  docs/debug_virt_stack/launch-qemu-gdb.md
  docs/debug_virt_stack/launch-qemu-strace.md
  docs/debug_virt_stack/logging.md
  docs/debug_virt_stack/privileged-node-debugging.md
  docs/debug_virt_stack/virsh-commands.md
Labels: size/XL, dco-signoff: yes, approved, lgtm

#741 Add pages for new section about virt debugging
  docs/.pages
  docs/debug_virt_stack/.pages
Labels: size/XS, dco-signoff: yes, approved, lgtm
