Repository kubevirt/user-guide, pull requests merged in 2023-12, with the labels that each got.

#742 docs, vm: Add network binding plugins guide
  docs/virtual_machines/.pages
  docs/virtual_machines/interfaces_and_networks.md
  docs/virtual_machines/net_binding_plugins/passt.md
  docs/virtual_machines/net_binding_plugins/slirp.md
  docs/virtual_machines/network_binding_plugins.md
Labels: size/XL, dco-signoff: yes, approved, lgtm

#744 Revert "IsolateEmulatorThread with full-pcpus-only (#736)"
  docs/virtual_machines/dedicated_cpu_resources.md
Labels: size/S, dco-signoff: yes, approved, lgtm

#746 docs, vm, network binding plugins: The network domain attachment option and its usage with macvtap
  docs/virtual_machines/interfaces_and_networks.md
  docs/virtual_machines/net_binding_plugins/macvtap.md
  docs/virtual_machines/network_binding_plugins.md
Labels: size/L, dco-signoff: yes, approved, lgtm

#748 Update macvtap docs
  docs/virtual_machines/interfaces_and_networks.md
Labels: size/S, dco-signoff: yes, approved, lgtm
