Repository kubevirt/user-guide, pull requests merged in 2023-10, with the labels that each got.

#697 Fix incorrect indentation for UEFI example (#696)
  docs/virtual_machines/virtual_hardware.md
Labels: size/XS, dco-signoff: yes, approved, lgtm, needs-ok-to-test

#708 Add note about writeback mode in disk cache
  docs/virtual_machines/disks_and_volumes.md
Labels: size/XS, dco-signoff: yes, approved, lgtm

#712 feat: add paragraph about deploying tekton pipelines in different namespace
  docs/virtual_machines/tekton_tasks.md
Labels: size/M, dco-signoff: yes, approved, lgtm

#723 Enabling footnotes feature
  mkdocs.yml
Labels: size/XS, dco-signoff: yes, approved, lgtm

#722 Adjust documentation for auto resource limits
  docs/virtual_machines/resources_requests_and_limits.md
Labels: size/M, dco-signoff: yes, approved, lgtm

#717 adding documentation regarding CPU hotplug
  docs/operations/.pages
  docs/operations/cpu_hotplug.md
Labels: size/L, dco-signoff: yes, approved, lgtm
