Repository kubevirt/user-guide, pull requests merged in 2023-02, with the labels that each got.

#641 Add prerequisites for the guest to get the correct MTU
  docs/virtual_machines/interfaces_and_networks.md
Labels: size/XS, dco-signoff: yes, approved, lgtm

#634 Fix selinux enabled
  Makefile
Labels: size/S, dco-signoff: yes, approved, lgtm

#640 Adds admonitions to architecture docs
  docs/architecture.md
Labels: size/S, dco-signoff: yes, approved, lgtm, ok-to-test

#642 Remove virtctl rename
  docs/virtual_machines/lifecycle.md
Labels: size/XS, dco-signoff: yes, approved, lgtm, ok-to-test

#643 Windows guest non virtio interfaces don't get the correct MTU
  docs/virtual_machines/interfaces_and_networks.md
Labels: size/XS, dco-signoff: yes, approved, lgtm

#645 Mtu table
  docs/virtual_machines/interfaces_and_networks.md
Labels: size/M, dco-signoff: yes, approved, lgtm

#644 feat: update kubevirt tekton tasks documentation
  docs/virtual_machines/tekton_tasks.md
Labels: size/S, dco-signoff: yes, approved, lgtm

#647 Add the metric list from all components to docs
  docs/operations/component_monitoring.md
Labels: size/XS, dco-signoff: yes, approved, lgtm

#648 feat(virtctl): Add documentation for the virtctl create vm command
  docs/virtual_machines/.pages
  docs/virtual_machines/creating_vms.md
Labels: size/L, dco-signoff: yes, approved, lgtm
