Repository kubevirt/user-guide, pull requests merged in 2024-02, with the labels that each got.

#759 Accessing Virtual Machines: Switch to cloudInitNoCloud
  docs/virtual_machines/accessing_virtual_machines.md
Labels: size/S, dco-signoff: yes, approved, lgtm

#756 Add Memory Hotplug Documentation
  docs/operations/.pages
  docs/operations/memory_hotplug.md
Labels: size/L, dco-signoff: yes, approved, lgtm

#761 instancetypes: Document inferFromVolumeFailurePolicy
  docs/virtual_machines/creating_vms.md
  docs/virtual_machines/instancetypes.md
Labels: size/M, dco-signoff: yes, approved, lgtm

#760 common-instancetypes: Add deployment instructions
  docs/operations/.pages
  docs/operations/deploy_common_instancetypes.md
  docs/operations/feature_gate_status_on_Arm64.md
  docs/virtual_machines/instancetypes.md
Labels: size/M, dco-signoff: yes, approved, lgtm

#714 runStrategy: Reword to be more focused on the VM behavior
  docs/virtual_machines/run_strategies.md
Labels: size/M, dco-signoff: yes, approved, lgtm

#765 networking: Update Multus example to use bridge CNI
  docs/virtual_machines/interfaces_and_networks.md
Labels: size/M, dco-signoff: yes, approved, lgtm

#766 Add migration API to the network binding plugin docs
  docs/virtual_machines/net_binding_plugins/passt.md
  docs/virtual_machines/network_binding_plugins.md
Labels: size/S, dco-signoff: yes, approved, lgtm

#763 kubevirt #11083 fix: broken formatting (and some editing)
  docs/operations/mediated_devices_configuration.md
Labels: size/L, dco-signoff: yes, approved, lgtm

#728 Run strategies: RerunOnFailure is now immutable
  docs/stylesheets/extra.css
  docs/virtual_machines/run_strategies.md
Labels: size/S, dco-signoff: yes, approved, lgtm

#767 netlify: break huge string
  netlify.toml
Labels: size/S, dco-signoff: yes, approved, lgtm
