Repository kubevirt/user-guide, pull requests merged in 2024-03, with the labels that each got.

#768 SR-IOV doc fixes
  docs/virtual_machines/interfaces_and_networks.md
Labels: size/S, sig/network, dco-signoff: yes, approved, lgtm, needs-ok-to-test

#751 User guide for hook sidecar
  docs/operations/.pages
  docs/operations/hook-sidecar.md
Labels: size/L, dco-signoff: yes, approved, lgtm, ok-to-test

#743 Fix file-not-found
  docs/virtual_machines/host-devices.md
Labels: lifecycle/stale, size/XS, dco-signoff: yes, approved, lgtm

#762 Drop 'Enabling cpu compatibility enforcement'
  docs/virtual_machines/virtual_hardware.md
Labels: size/S, dco-signoff: yes, approved, lgtm

#758 VM rollout strategy
  docs/operations/.pages
  docs/operations/cpu_hotplug.md
  docs/operations/memory_hotplug.md
  docs/operations/vm_rollout_strategies.md
Labels: size/L, dco-signoff: yes, approved, lgtm

#774 Typo: s/,/./
  docs/operations/cpu_hotplug.md
Labels: size/XS, dco-signoff: yes, approved, lgtm

#777 Contribfest: Moving guestfs.md from kubevirt/docs to user-guide
  docs/virtual_machines/.pages
  docs/virtual_machines/guestfs.md
Labels: size/L, dco-signoff: yes, approved, lgtm

#772 persistent reservation: add security note
  docs/virtual_machines/disks_and_volumes.md
Labels: size/XS, dco-signoff: yes, approved, lgtm
