Repository kubevirt/user-guide, pull requests merged in 2024-10, with the labels that each got.

#836 docs: fix spelling mistakes - interfaces_and_networks.md
  docs/network/interfaces_and_networks.md
Labels: size/XS, dco-signoff: yes, approved, lgtm, ok-to-test, needs-approver-review

#845 Live Migration: Add primary pod NIC name limitation
  docs/compute/live_migration.md
Labels: size/XS, dco-signoff: yes, approved, lgtm

#841 operations, network: Declare network hotplug feature as GA
  docs/network/hotplug_interfaces.md
Labels: size/S, dco-signoff: yes, approved, lgtm, needs-approver-review

#842 docs, network, binding-plugins: Add a limited support note and bump to Beta
  docs/network/network_binding_plugins.md
Labels: size/S, dco-signoff: yes, approved, lgtm

#849 Change spec.running refs to runStrategy
  docs/architecture.md
  docs/cluster_admin/ksm.md
  docs/cluster_admin/scheduler.md
  docs/compute/numa.md
  docs/compute/run_strategies.md
  docs/network/hotplug_interfaces.md
  docs/network/net_binding_plugins/macvtap.md
  docs/network/net_binding_plugins/passt.md
  docs/network/net_binding_plugins/slirp.md
  docs/network/network_binding_plugins.md
  docs/storage/disks_and_volumes.md
  docs/storage/export_api.md
  docs/user_workloads/accessing_virtual_machines.md
  docs/user_workloads/instancetypes.md
  docs/user_workloads/pool.md
  docs/user_workloads/startup_scripts.md
  docs/user_workloads/templates.md
Labels: size/M, dco-signoff: yes, approved, lgtm
