Repository kubevirt/user-guide, pull requests merged in 2024-07, with the labels that each got.

#813 passt: Add memory overhead
  docs/network/net_binding_plugins/passt.md
Labels: size/XS, dco-signoff: yes, approved, lgtm

#814 Network binding plugins: Add compute resource overhead
  docs/network/network_binding_plugins.md
Labels: size/M, dco-signoff: yes, approved, lgtm

#805 Document update volume strategy and volume migration
  docs/storage/disks_and_volumes.md
  docs/storage/volume_migration.md
Labels: size/L, dco-signoff: yes, approved, lgtm

#811 role tagging: Fix example
  docs/user_workloads/startup_scripts.md
Labels: size/XS, dco-signoff: yes, approved, lgtm

#812 Adding the release notes for v1.3
  docs/release_notes.md
Labels: size/L, dco-signoff: yes, approved, lgtm

#819 owners, user-guide: set up owners from sigs
  OWNERS
  OWNERS_ALIASES
  docs/cluster_admin/OWNERS
  docs/compute/OWNERS
  docs/debug_virt_stack/OWNERS
  docs/network/OWNERS
  docs/storage/OWNERS
Labels: size/L, dco-signoff: yes, approved, lgtm

#816 Fix typo in path for numa guestMappingPassthrough
  docs/compute/numa.md
Labels: size/XS, dco-signoff: yes, approved, lgtm, needs-ok-to-test

#804 Fix Markdown formatting
  docs/compute/resources_requests_and_limits.md
Labels: size/XS, dco-signoff: yes, approved, lgtm, ok-to-test

#783 fix cdrom readonly field
  docs/storage/disks_and_volumes.md
Labels: size/XS, dco-signoff: yes, approved, lgtm, needs-ok-to-test

#823 Adding aburden as approver; removing jobbler as reviewer
  OWNERS_ALIASES
Labels: size/S, dco-signoff: yes, approved, lgtm
