Repository kubevirt/user-guide, pull requests merged in 2024-06, with the labels that each got.

#798 Replace usage of DataVolume.spec.pvc with .storage
  docs/storage/disks_and_volumes.md
  docs/storage/hotplug_volumes.md
  docs/user_workloads/instancetypes.md
  docs/user_workloads/startup_scripts.md
  docs/user_workloads/templates.md
Labels: size/M, dco-signoff: yes, approved, lgtm

#806 operations, network: Declare network hotplug feature as Beta
  docs/network/hotplug_interfaces.md
Labels: size/XS, dco-signoff: yes, approved, lgtm

#809 snapshot and export APIs to beta
  docs/storage/export_api.md
  docs/storage/snapshot_restore_api.md
Labels: size/M, dco-signoff: yes, approved, lgtm

#773 NUMA.md add Additional Reading section
  README.md
  docs/compute/numa.md
Labels: size/S, dco-signoff: yes, approved, lgtm, needs-ok-to-test

#808 node assignment: add paragraph about live updates
  docs/compute/node_assignment.md
Labels: size/S, dco-signoff: yes, approved, lgtm

#797 Fix typo: ymal ⇒ yaml
  docs/debug_virt_stack/privileged-node-debugging.md
Labels: size/XS, dco-signoff: yes, approved, lgtm, needs-ok-to-test

#810 Update virtctl_client_tool.md
  docs/user_workloads/virtctl_client_tool.md
Labels: size/XS, dco-signoff: yes, approved, lgtm, needs-ok-to-test
