Repository kubevirt/user-guide, pull requests merged in 2025-01, with the labels that each got.

#861 fix(virtctl): Use correct flag for sysprep volume in example
  docs/user_workloads/creating_vms.md
Labels: size/XS, dco-signoff: yes, approved, lgtm

#830 Update persistent TPM & UEFI page to clarify storageclass requirements
  docs/compute/persistent_tpm_and_uefi_state.md
Labels: size/XS, dco-signoff: yes, approved, lgtm, ok-to-test

#847 common-instancetypes: Remove FG and update docs
  docs/user_workloads/deploy_common_instancetypes.md
Labels: size/S, dco-signoff: yes, approved, lgtm, needs-approver-review

#837 Removing Alona and cwilkers from reviewers and approvers
  OWNERS
  OWNERS_ALIASES
Labels: lifecycle/stale, size/XS, dco-signoff: yes, approved, lgtm

#854 (migration_policies) fix wrong spec indentation
  docs/cluster_admin/migration_policies.md
Labels: size/XS, dco-signoff: yes, approved, lgtm, ok-to-test

#858 chore: replace device name for disks with bus type virtio as dev name is unsupported
  docs/user_workloads/startup_scripts.md
Labels: size/XS, dco-signoff: yes, approved, lgtm, ok-to-test

#838 docs: fix yaml indenting on intallation.md
  docs/cluster_admin/installation.md
Labels: lifecycle/stale, size/XS, dco-signoff: yes, approved, lgtm, needs-ok-to-test
