Repository kubevirt/user-guide, pull requests merged in 2025-03, with the labels that each got.

#873 Removing need for VolumeUpdateStrategy and VolumeMigration feature gates
  docs/storage/volume_migration.md
Labels: size/XS, dco-signoff: yes, approved, lgtm

#840 Update volume migration doc
  docs/storage/.pages
  docs/storage/volume_migration.md
Labels: lifecycle/stale, size/S, dco-signoff: yes, approved, lgtm, needs-approver-review

#871 virtctl: Cleanups to accessing VMs with virtctl ssh
  docs/user_workloads/accessing_virtual_machines.md
Labels: size/M, dco-signoff: yes, approved, lgtm, needs-approver-review

#864 network: Add link state management section
  docs/network/interfaces_and_networks.md
Labels: size/M, dco-signoff: yes, approved, lgtm

#872 Adding v1.5 release notes to docs
  docs/release_notes.md
Labels: size/L, sig/storage, sig/network, dco-signoff: yes, approved, lgtm, sig/release, sig/compute, sig/scale, sig/observability

#879 instancetype: Add InstancetypeReferencePolicy docs
  docs/user_workloads/instancetypes.md
Labels: size/M, dco-signoff: yes, approved, lgtm
