Repository kubevirt/user-guide, pull requests merged in 2025-05, with the labels that each got.

#839 Update VM instead of VMI when exposing service objects
  docs/network/service_objects.md
Labels: lifecycle/rotten, size/XS, sig/network, dco-signoff: yes, approved, lgtm, needs-ok-to-test

#889 Document supplementalPool iothreads policy
  docs/storage/disks_and_volumes.md
Labels: size/M, dco-signoff: yes, approved, lgtm, needs-approver-review

#883 Fixed broken examples of liveness and readiness probes (#865)
  docs/user_workloads/liveness_and_readiness_probes.md
Labels: size/L, dco-signoff: yes, approved, lgtm, needs-ok-to-test, needs-approver-review

#895 Document how to run legacy Windows versions
  docs/user_workloads/.pages
  docs/user_workloads/legacy_windows.md
Labels: size/M, dco-signoff: yes, approved, lgtm

#890 chore(doc): document missing features in vmsnapshotrestores
  docs/storage/clone_api.md
  docs/storage/snapshot_restore_api.md
Labels: size/M, dco-signoff: yes, approved, lgtm, needs-ok-to-test, needs-approver-review

#897 CPU hotplug: Add net multi-queue limitation
  docs/compute/cpu_hotplug.md
Labels: size/S, dco-signoff: yes, approved, lgtm
