Repository kubevirt/user-guide, pull requests merged in 2025-07, with the labels that each got.

#899 feat(snapshot_api): add new volumeRestoreOverrides/volumeRestorePolic…
  docs/storage/snapshot_restore_api.md
Labels: size/M, dco-signoff: yes, approved, lgtm, needs-ok-to-test

#909 cluster_admin: Remove s390x and arm64 specific nightly installation docs
  docs/cluster_admin/installation.md
Labels: size/S, dco-signoff: yes, approved, lgtm

#903 Export: Update vmexport docs with new flags
  docs/storage/export_api.md
Labels: size/M, dco-signoff: yes, approved, lgtm, needs-approver-review
