Repository kubevirt/user-guide, pull requests merged in 2025-02, with the labels that each got.

#866 virtiofs: Update feature gate usage, privileged containers and live migration
  docs/storage/disks_and_volumes.md
Labels: size/M, dco-signoff: yes, approved, lgtm

#829 Update virtual_hardware.md
  docs/compute/virtual_hardware.md
Labels: lifecycle/rotten, size/XS, dco-signoff: yes, approved, lgtm, needs-ok-to-test

#859 Change clone API version from v1alpha1 to v1beta1
  docs/storage/clone_api.md
Labels: size/XS, dco-signoff: yes, approved, lgtm

#863 Document the AllowWorkloadDisruption migration option
  docs/compute/live_migration.md
Labels: size/M, dco-signoff: yes, approved, lgtm
