Repository kubevirt/user-guide, pull requests merged in 2025-08, with the labels that each got.

#912 docs(compute): update persistent_tpm_and_uefi_state.md
  docs/compute/persistent_tpm_and_uefi_state.md
Labels: size/S, dco-signoff: yes, approved, lgtm, ok-to-test

#910 confidential computing: Add guide for running IBM Secure Execution VM
  docs/cluster_admin/confidential_computing.md
Labels: size/M, dco-signoff: yes, approved, lgtm

#898 fix(storage): typo in `lun` section
  docs/storage/disks_and_volumes.md
Labels: lifecycle/stale, size/XS, dco-signoff: yes, approved, lgtm, needs-ok-to-test

#905 VMSnapshot: add better documentation on snapshot verification - included,excluded volumes and snapshot indications
  docs/storage/snapshot_restore_api.md
Labels: size/S, dco-signoff: yes, approved, lgtm

#906 Update docs for declarative hotplug with virtio bus support
  docs/storage/disks_and_volumes.md
  docs/storage/hotplug_volumes.md
Labels: size/L, dco-signoff: yes, approved, lgtm, needs-approver-review

#915 accessing_virtual_machines: Remove virtctl local ssh flag
  docs/user_workloads/accessing_virtual_machines.md
Labels: size/XS, dco-signoff: yes, approved, lgtm
