Repository kubevirt/user-guide, pull requests merged in 2025-06, with the labels that each got.

#893 Add a note about VMIM hardening in NIC hotplug docs
  docs/network/hotplug_interfaces.md
Labels: size/XS, dco-signoff: yes, approved, lgtm, needs-ok-to-test, needs-approver-review

#902 instancetype: Clean up docs ahead of v1.6.0 release
  docs/user_workloads/instancetypes.md
Labels: size/M, dco-signoff: yes, approved, lgtm

#900 net, hotplug: Add note about auto migration
  docs/network/hotplug_interfaces.md
Labels: size/XS, dco-signoff: yes, approved, lgtm, needs-approver-review
